#!/usr/bin/env python
# Crichton, Admirable Source Configuration Management
# Copyright 2012 British Broadcasting Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#

import os
import sys
from os.path import dirname, abspath, join

sys.path.append("/usr/local/crichtonweb")
sys.path.append("/usr/local")

os.environ['DJANGO_SETTINGS_MODULE'] = 'crichtonweb.settings'

from django.contrib.auth.models import User

username = sys.argv[1]
password = sys.argv[2]
email = sys.argv[3]

if User.objects.filter(username=username).exists():
    user = User.objects.get(username=username)
    user.set_password(password)
    user.email = email
    user.save()
else:
    User.objects.create_superuser(username, email, password)
