#!/bin/sh
# Crichton, Admirable Source Configuration Management
# Copyright 2012 British Broadcasting Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#
ARG=$1

PATH=/bin:/usr/bin:/usr/local/bin

# Facter doesn't allow custom facts to be selectable by argument
# so we fake it with a grep
if [ -n "${ARG}" ] ; then
  FACTERLIB=/var/lib/puppet/lib/facter /usr/bin/facter | grep -w ${ARG}
else
  FACTERLIB=/var/lib/puppet/lib/facter /usr/bin/facter
fi
