#!/usr/bin/env bash
# Crichton, Admirable Source Configuration Management
# Copyright 2012 British Broadcasting Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#

curl -s -o css/jquery-ui-cupertino-1.8.12.css \
    https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/themes/cupertino/jquery-ui.css
curl -s -o js/jquery-ui-1.8.12.js \
    https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js
curl -s -o js/jquery-1.6.1.min.js \
    http://code.jquery.com/jquery-1.6.1.min.js
curl -s -o js/jquery.form-2.7.2.js \
    https://github.com/malsup/form/raw/5d413a0169b673c9ee81d5f458b1c955ff1b8027/jquery.form.js
echo "Do you need to update css/images with the cupertino images for jquery ui?"
svn status | egrep '^\?' | sed -e 's/^\? *//g' | xargs svn add
svn status
