#!/bin/bash
# Crichton, Admirable Source Configuration Management
# Copyright 2012 British Broadcasting Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#

# fake /sbin/service with some validity checks
# Taken from bbc-remote-deploy rpm, with minor modifications to validity checks

SERVICE=$1
CMD=$2

PATH=/usr/local/bin:/bin:/usr/bin:/sbin:/usr/srbin

fail() {
  echo FATAL - service failed! $@
  exit 1
}
trap fail ERR

[ -z ${SERVICE} ] || [ -z ${CMD} ] && fail "usage: restart-apache httpd-something"
echo ${SERVICE} | egrep -q '^(apache|bbc|httpd|tomcat)' || fail "${SERVICE} doesn't match list of permitted services"
[ -x /etc/init.d/${SERVICE} ] || fail "${SERVICE} doesn't have an /etc/init.d script"

sudo /sbin/service ${SERVICE} ${CMD}

